const countries = [
    {id: 0, name: 'Argentina', code: 'ar'},
    {id: 1, name: 'Australia', code:'au'},
    {id: 2, name:'Austria', code:'at'},
    {id: 3, name: 'Belgium', code:'be'},
    {id: 4, name: 'Brazil', code:'br'},
    {id: 5, name: 'Bulgaria', code: 'bg'},
    {id: 6, name: 'Canada', code: 'ca'},
    {id: 7, name: 'China', code: 'cn'},
    {id: 8, name: 'Colombia', code: 'co'},
    {id: 9, name: 'Cuba', code: 'cu'},
    {id: 10, name: 'Czech Republic', code: 'cz'},
    {id: 11, name: 'Egypt', code: 'eg'},
    {id: 12, name: 'France', code: 'fr'},
    {id: 13, name: 'Germany', code: 'de'},
    {id: 14, name: 'Greece', code: 'gr'},
    {id: 15, name: 'Hong Kong', code: 'hk'},
    {id: 16, name: 'Hungary', code: 'hu'},
    {id: 17, name: 'India', code: 'in'},
    {id: 18, name: 'Indonesia', code: 'id'},
    {id: 19, name: 'Ireland', code: 'ie'},
    {id: 20, name: 'Isreal', code: 'il'},
    {id: 21, name: 'Italy', code: 'it'},
    {id: 22, name: 'Japan', code: 'jp'},
    {id: 23, name: 'Latvia', code: 'lv'},
    {id: 24, name: 'Lithunia', code: 'lt'},
    {id: 25, name: 'Malaysia', code: 'my'},
    {id: 26, name: 'Mexico', code: 'mx'},
    {id: 27, name: 'Morocco', code: 'ma'},
    {id: 28, name: 'Netherlands', code: 'nl'},
    {id: 29, name: 'New Zealand', code: 'nz'},
    {id: 30, name: 'Nigeria', code: 'ng'},
    {id: 31, name: 'Norway', code: 'no'},
    {id: 32, name: 'Philippines', code: 'ph'},
    {id: 33, name: 'Poland', code: 'pl'},
    {id: 34, name: 'Portugal', code: 'pt'},
    {id: 35, name: 'Romania', code: 'ro'},
    {id: 36, name: 'Russia', code: 'ru'},
    {id: 37, name: 'Saudia Arabia', code: 'sa'},
    {id: 38, name: 'Serbia', code: 'rs'},
    {id: 39, name: 'Singapore', code: 'sg'},
    {id: 40, name: 'Slovakia', code: 'sk'},
    {id: 41, name: 'Slovenia', code: 'si'},
    {id: 42, name: 'South Africa', code: 'za'},
    {id: 43, name: 'South Korea', code: 'kr'},
    {id: 44, name: 'Sweden', code: 'se'},
    {id: 45, name: 'Switzerland', code: 'ch'},
    {id: 46, name: 'Taiwan', code: 'tw'},
    {id: 47, name: 'Thailand', code: 'th'},
    {id: 48, name: 'Turkey', code: 'tr'},
    {id: 49, name: 'UAE', code: 'ae'},
    {id: 50, name: 'Ukraine', code: 'ua'},
    {id: 51, name: 'United Kingdom', code: 'gb'},
    {id: 52, name: 'United States', code: 'us'},
    {id: 53, name: 'Venuzuela', code: 've'},
]

export default countries