const API_KEY = "b6e641af06934ab7a9472d1d83c8d503"

const requests = {
    general: `top-headlines?country=us&category=general&apiKey=${API_KEY}`,
    health: `top-headlines?country=in&category=health&apiKey=${API_KEY}`,
    sports: `top-headlines?country=in&category=sports&apiKey=${API_KEY}`,
    entertainment: `top-headlines?country=in&category=entertainment&apiKey=${API_KEY}`,
    business: `top-headlines?country=in&category=business&apiKey=${API_KEY}`,
    tech: `top-headlines?country=in&category=technology&apiKey=${API_KEY}`,
    tnb: `everything?domains=thenextweb.com&apiKey=${API_KEY}`,
    gnews: `top-headlines?sources=google-news-in&apiKey=${API_KEY}`,
    ae: `top-headlines?country=ae&apiKey=${API_KEY}`,
    ar: `top-headlines?country=ar&apiKey=${API_KEY}`,
    at: `top-headlines?country=at&apiKey=${API_KEY}`,
    au: `top-headlines?country=au&apiKey=${API_KEY}`,
    be: `top-headlines?country=be&apiKey=${API_KEY}`,
    bg: `top-headlines?country=bg&apiKey=${API_KEY}`,
    br: `top-headlines?country=br&apiKey=${API_KEY}`,
    ca: `top-headlines?country=ca&apiKey=${API_KEY}`,
    ch: `top-headlines?country=ch&apiKey=${API_KEY}`,
    cn: `top-headlines?country=cn&apiKey=${API_KEY}`,
    co: `top-headlines?country=co&apiKey=${API_KEY}`,
    cu: `top-headlines?country=cu&apiKey=${API_KEY}`,
    cz: `top-headlines?country=cz&apiKey=${API_KEY}`,
    de: `top-headlines?country=de&apiKey=${API_KEY}`,
    eg: `top-headlines?country=eg&apiKey=${API_KEY}`,
    fr: `top-headlines?country=fr&apiKey=${API_KEY}`,
    gb: `top-headlines?country=gb&apiKey=${API_KEY}`,
    gr: `top-headlines?country=gr&apiKey=${API_KEY}`,
    hk: `top-headlines?country=hk&apiKey=${API_KEY}`,
    hu: `top-headlines?country=hu&apiKey=${API_KEY}`,
    id: `top-headlines?country=id&apiKey=${API_KEY}`,
    ie: `top-headlines?country=ie&apiKey=${API_KEY}`,
    il: `top-headlines?country=il&apiKey=${API_KEY}`,
    in: `top-headlines?country=in&apiKey=${API_KEY}`,
    it: `top-headlines?country=it&apiKey=${API_KEY}`,
    jp: `top-headlines?country=jp&apiKey=${API_KEY}`,
    kr: `top-headlines?country=kr&apiKey=${API_KEY}`,
    lt: `top-headlines?country=lt&apiKey=${API_KEY}`,
    lv: `top-headlines?country=lv&apiKey=${API_KEY}`,
    ma: `top-headlines?country=ma&apiKey=${API_KEY}`,
    mx: `top-headlines?country=mx&apiKey=${API_KEY}`,
    my: `top-headlines?country=my&apiKey=${API_KEY}`,
    ng: `top-headlines?country=ng&apiKey=${API_KEY}`,
    nl: `top-headlines?country=nl&apiKey=${API_KEY}`,
    no: `top-headlines?country=no&apiKey=${API_KEY}`,
    nz: `top-headlines?country=nz&apiKey=${API_KEY}`,
    ph: `top-headlines?country=ph&apiKey=${API_KEY}`,
    pl: `top-headlines?country=pl&apiKey=${API_KEY}`,
    pt: `top-headlines?country=pt&apiKey=${API_KEY}`,
    ro: `top-headlines?country=ro&apiKey=${API_KEY}`,
    rs: `top-headlines?country=rs&apiKey=${API_KEY}`,
    ru: `top-headlines?country=ru&apiKey=${API_KEY}`,
    sa: `top-headlines?country=sa&apiKey=${API_KEY}`,
    se: `top-headlines?country=se&apiKey=${API_KEY}`,
    sg: `top-headlines?country=sg&apiKey=${API_KEY}`,
    si: `top-headlines?country=si&apiKey=${API_KEY}`,
    sk: `top-headlines?country=sk&apiKey=${API_KEY}`,
    th: `top-headlines?country=th&apiKey=${API_KEY}`,
    tr: `top-headlines?country=tr&apiKey=${API_KEY}`,
    tw: `top-headlines?country=tw&apiKey=${API_KEY}`,
    ua: `top-headlines?country=ua&apiKey=${API_KEY}`,
    us: `top-headlines?country=us&apiKey=${API_KEY}`,
    ve: `top-headlines?country=ve&apiKey=${API_KEY}`,
    za: `top-headlines?country=za&apiKey=${API_KEY}`,
}

export default requests